# Generated by Django 2.1.1 on 2018-09-23 18:05

from django.db import migrations, models
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_bid_name_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['event__datetime', 'speedrun__starttime', 'parent__name', 'name'], 'permissions': (('top_level_bid', 'Can create new top level bids'), ('delete_all_bids', 'Can delete bids with donations attached'), ('view_hidden', 'Can view hidden bids'))},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'datetime', 'ordering': ('datetime', 'name'), 'permissions': (('can_edit_locked_events', 'Can edit locked events'),)},
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ['event__datetime', 'startrun__starttime', 'starttime', 'name']},
        ),
        migrations.AlterModelOptions(
            name='speedrun',
            options={'ordering': ['event__datetime', 'order', 'name'], 'permissions': (('can_view_tech_notes', 'Can view tech notes'),), 'verbose_name': 'Speed Run'},
        ),
        migrations.AddField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='speedrun',
            name='order',
            field=models.IntegerField(blank=True, help_text='Please note that using the schedule editor is much easier', null=True, validators=[tracker.validators.positive]),
        ),
    ]
