# Generated by Django 2.2.10 on 2020-03-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_donor_cache_tweaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='horaro_category_col',
            field=models.IntegerField(blank=True, help_text='Column index for category info (start at 0)', null=True, verbose_name='Category Column'),
        ),
        migrations.AddField(
            model_name='event',
            name='horaro_commentators_col',
            field=models.IntegerField(blank=True, help_text='Column index for commentator info (start at 0)', null=True, verbose_name='Commentators Column'),
        ),
        migrations.AddField(
            model_name='event',
            name='horaro_game_col',
            field=models.IntegerField(blank=True, help_text='Column index for game info (start at 0)', null=True, verbose_name='Game Column'),
        ),
        migrations.AddField(
            model_name='event',
            name='horaro_id',
            field=models.CharField(blank=True, default='', help_text='ID or slug for Horaro event', max_length=100, verbose_name='Event ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='horaro_runners_col',
            field=models.IntegerField(blank=True, help_text='Column index for runner info (start at 0)', null=True, verbose_name='Runners Column'),
        ),
    ]
