# Generated by Django 5.0.2 on 2024-11-24 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tracker', '0009_auto_20200302_1011'),
        ('tracker', '0048_remove_old_ad_permission'),
    ]

    operations = []
